# Generated by Django 5.1.5 on 2025-02-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0002_facility_bus_facilities_order_trip_ticket_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("seat",)},
        ),
    ]
