# Generated by Django 5.1.5 on 2025-02-02 12:37

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_alter_ticket_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="image",
            field=models.ImageField(null=True, upload_to=station.models.bus_image_path),
        ),
    ]
